### ISSUE TITLE
Support ruby 2.3.x/2.2.x

### ISSUE THREAD

**Issue by 0xdevalias** [usualoma/ruby-with-therubyracer#2]
It would be awesome if there were supported images for ruby 2.3.x/2.2.x as well as 2.4.x

A project i'm working on is currently running on 2.3.x, we're not quite ready to upgrade to 2.4.x, but would still love to be able to build our images from alpine.

I'm happy to take a look at making this work if you're open to it. Wanted to check first, and confirm whether there was any reason why you think it wouldn't work, before I invest the time/effort.

**Comment by usualoma** [comment]
Okey.
I was added dockerfiles for ruby 2.2.6/2.3.3 at 51073b2 with some tweaks at 6514285.

**Comment by 0xdevalias** [comment]
Legend! Thanks for the quick response! Will try it out this evening! <3

**Comment by 0xdevalias** [comment]
Seems to work from what I can see so far. Will open another issue if I have any issues. Thanks again!
